services:
  messageboard:
    build: .
    volumes:
      - .:/application
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: "postgres"
    env_file:
      - .env
    volumes:
      - database-data:/var/lib/postgresql/data
volumes:
  database-data:
